In [2]:
import sklearn.datasets
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [3]:
tumour=sklearn.datasets.load_breast_cancer()
tumour.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [4]:
tumour['feature_names']

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [5]:
tumour['target_names']#where 0 represents malignant tumors and 1 represents benign tumors

array(['malignant', 'benign'], dtype='<U9')

In [6]:

X,y=tumour['data'],tumour['target']
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=0)


In [7]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
#n=np.arange(10,20,1)
#for i in n:
knn=KNeighborsClassifier(n_neighbors=12)#12 has the best score
knn.fit(X_train,y_train)
y_pred1=knn.predict(X_test)
#print(i)
print(knn.score(X_train,y_train))
print(knn.score(X_test,y_test))
print(confusion_matrix(y_test,y_pred1))
    

0.9413145539906104
0.958041958041958
[[49  4]
 [ 2 88]]


In [8]:
from sklearn.linear_model import LogisticRegression
log_reg=LogisticRegression()
log_reg.fit(X_train,y_train)
y_pred2=log_reg.predict(X_test)
print(log_reg.score(X_train,y_train))
print(log_reg.score(X_test,y_test))
print(confusion_matrix(y_test,y_pred2))

0.9577464788732394
0.958041958041958
[[52  1]
 [ 5 85]]


In [9]:
from sklearn.tree import DecisionTreeClassifier
tree=DecisionTreeClassifier(max_depth=5)
tree.fit(X_train,y_train)
y_pred3=tree.predict(X_test)
print(tree.score(X_train,y_train))
print(tree.score(X_test,y_test))
print(confusion_matrix(y_test,y_pred3))

0.9929577464788732
0.9230769230769231
[[49  4]
 [ 7 83]]


In [10]:
from sklearn.ensemble import RandomForestClassifier
rforest=RandomForestClassifier()
rforest.fit(X_train,y_train)
y_pred4=rforest.predict(X_test)
print(rforest.score(X_train,y_train))
print(rforest.score(X_test,y_test))
print(confusion_matrix(y_test,y_pred4))

1.0
0.9790209790209791
[[52  1]
 [ 2 88]]


In [13]:
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train1 = scaler.fit_transform(X_train)
X_test1 = scaler.transform(X_test)
svm = SVC(kernel='rbf', C=10)
svm.fit(X_train1,y_train)
y_pred5=svm.predict(X_test1)
print(svm.score(X_train1,y_train))
print(svm.score(X_test1,y_test))
print(confusion_matrix(y_test,y_pred5))

0.9882629107981221
0.993006993006993
[[52  1]
 [ 0 90]]


In [32]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(100), max_iter=300,activation = 'relu',solver='adam',random_state=1)
mlp.fit(X_train1,y_train)
y_pred6=mlp.predict(X_test1)
print(mlp.score(X_train1,y_train))
print(mlp.score(X_test1,y_test))
print(confusion_matrix(y_test,y_pred6))

0.9976525821596244
0.965034965034965
[[51  2]
 [ 3 87]]
